// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/about"
    | "/concepts"
    | "/dag"
    | "/lean"
    | "/production"
    | "/sources"
    | `/sources/${string}`
    | `/u/${string}`
    | "/units"
  }
}

export {};
