// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/about"
    | "/biology"
    | `/biology/${string}`
    | "/chemistry"
    | `/chemistry/${string}`
    | "/concepts"
    | "/connections"
    | "/dag"
    | "/lean"
    | "/math"
    | "/philosophy"
    | `/philosophy/${string}`
    | "/physics"
    | "/plans"
    | `/plans/${string}`
    | "/production"
    | "/sources"
    | `/sources/${string}`
    | "/specs"
    | `/specs/${string}`
    | `/u/${string}`
    | "/units"
  }
}

export {};
