/-
  Codex.AlgGeom.Tropical.TropicalCurve

  Companion Lean module for `04.12.02 Tropical curve as balanced rational
  metric graph`.

  Mikhalkin 2005 — *Enumerative tropical algebraic geometry in R^2*,
  J. Amer. Math. Soc. 18, 313–377 (definition via balanced rational
  polyhedral 1-complexes in R^n; correspondence with classical
  enumerative invariants in R^2). Maclagan–Sturmfels 2015 —
  *Introduction to Tropical Geometry*, Graduate Studies in Mathematics
  161, Ch. 3 (canonical exposition of tropical curves and their
  intersection theory). Brannetti–Melo–Viviani 2011 — *On the tropical
  Torelli map*, Adv. Math. 226, 2546–2586 (abstract tropical curves as
  weighted metric graphs and the moduli space of tropical curves).
  Baker–Norine 2007 — *Riemann–Roch and Abel–Jacobi theory on a finite
  graph*, Adv. Math. 215, 766–788 (tropical Riemann–Roch theorem).

  Statement: a *tropical curve in R^n* is a balanced rational 1-
  dimensional polyhedral complex Γ ⊂ R^n: finitely many edges with
  rational primitive direction vectors, each edge carrying a positive
  integer weight, satisfying the *balancing condition*
    Σ_{e ∋ v} w_e · u_{e, v} = 0 ∈ Z^n
  at every vertex v, where u_{e, v} ∈ Z^n is the primitive integer
  vector pointing along e away from v. Equivalently, an *abstract
  tropical curve* is a finite metric graph (G, ℓ) with edge weights
  w : E(G) → ℤ_{> 0} and edge lengths ℓ : E(G) → ℝ_{> 0} ∪ {∞}; the
  underlying topological space is the metric realisation. The *genus*
  is g(Γ) = b₁(Γ) = |E| − |V| + 1 for connected Γ. The Baker–Norine
  tropical Riemann–Roch theorem states r(D) − r(K − D) = deg(D) − g + 1
  for every divisor D on Γ.

  lean_status: partial. Mathlib has multisets, finite graphs as
  SimpleGraph, and integer-valued lattice infrastructure, but does not
  yet ship: (i) rational polyhedral 1-complexes with integer weights;
  (ii) the balancing condition as a named predicate on a finite vertex
  set; (iii) the metric-graph realisation of an abstract weighted
  metric graph; (iv) the genus of a tropical curve as the first Betti
  number of its underlying topological space; (v) the tropical Picard
  group and Riemann–Roch divisor formalism. We state the central
  definitions and theorems with placeholder predicates so that
  downstream files can refer to the named statements.
-/

import Mathlib.Algebra.BigOperators.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Multiset.Basic

namespace Codex.AlgGeom.Tropical

open BigOperators

/-!
## §1 — Tropical curves in R^n via balanced polyhedral complexes

A *primitive integer vector* in `ℤ^n` is a non-zero vector whose
component gcd equals 1. Every line through the origin with rational
slope is generated by a unique pair `±u` of primitive integer vectors.
An *edge of a tropical curve* in `ℝ^n` is a line segment (possibly
unbounded) with rational direction; together with a positive integer
weight `w` and the choice of primitive direction `u`, it records the
weighted-direction datum `w · u ∈ ℤ^n` at each of its two endpoints
(with opposite signs).
-/

/-- A *primitive integer vector* in dimension `n`: a non-zero vector
`u : Fin n → ℤ` whose coordinate gcd equals one. The mathematical role
is to record the rational direction of an edge of a tropical curve, up
to sign: every rational direction has a unique primitive representative
up to `±1`. -/
structure PrimitiveVector (n : ℕ) where
  /-- Underlying integer vector. -/
  coord : Fin n → ℤ
  /-- Primitivity witness: vector is non-zero and gcd of coordinates is 1. -/
  primitive_witness : True

/-- A *weighted primitive direction* in dimension `n`: a positive
integer weight together with a primitive integer direction vector.
Mathematically encodes a single endpoint-side contribution of an edge
to the balancing sum at one of its endpoints. -/
structure WeightedDirection (n : ℕ) where
  /-- Positive integer edge weight. -/
  weight : ℕ
  /-- Weight is strictly positive (witness). -/
  weight_pos : 0 < weight
  /-- Primitive direction vector pointing away from the chosen vertex. -/
  direction : PrimitiveVector n

/-- The *signed coordinate vector* of a weighted direction:
the integer vector `w · u ∈ ℤ^n`. This is the quantity that appears in
the balancing condition: at each vertex, the sum of the signed
coordinate vectors of all incident weighted directions vanishes. -/
def WeightedDirection.signed {n : ℕ}
    (d : WeightedDirection n) : Fin n → ℤ :=
  fun i => (d.weight : ℤ) * d.direction.coord i

/-- An *abstract tropical-curve vertex datum* in dimension `n`: a
multiset of weighted primitive directions (the edges incident to the
vertex, each viewed with its primitive direction pointing away from the
vertex and weighted by its tropical edge multiplicity). -/
structure VertexData (n : ℕ) where
  /-- Multiset of incident weighted directions. -/
  incident : Multiset (WeightedDirection n)

/-- The *balancing condition* at a single vertex: the sum over incident
weighted directions of the signed coordinate vectors is the zero vector
in `ℤ^n`. Mikhalkin 2005 — central definition. -/
def VertexData.balanced {n : ℕ} (v : VertexData n) : Prop :=
  ∀ i : Fin n,
    (v.incident.map (fun d => d.signed i)).sum = 0

/-!
## §2 — Tropical curves as global structures

A *tropical curve in R^n* assembles vertex data into a coherent global
1-complex: finitely many vertices, each carrying a `VertexData n`, and
a consistency condition that the directions at neighbouring vertices
along a common edge are opposite. We record the structure abstractly.
-/

/-- A *tropical curve in `ℝ^n`* is a finite collection of vertices,
each with vertex data, plus a balancing axiom at every vertex.

This is the Mikhalkin definition: a rational 1-dimensional polyhedral
complex `Γ ⊂ ℝ^n` whose edges carry positive integer weights and which
satisfies the balancing condition at every vertex. -/
structure TropicalCurve (n : ℕ) where
  /-- Finite set of vertices, modelled as a finite type. -/
  V : Type*
  /-- Finiteness of the vertex set. -/
  fintype_V : Fintype V
  /-- Vertex data at each vertex (the incident weighted directions). -/
  vertexData : V → VertexData n
  /-- Global balancing axiom: every vertex satisfies the balancing
  condition individually. -/
  balanced : ∀ v : V, (vertexData v).balanced

/-- **Balancing is necessary for a tropical curve.** A definitional
consequence: by construction, every `TropicalCurve` satisfies the
balancing condition at each of its vertices. -/
theorem tropicalCurve_balanced {n : ℕ} (Γ : TropicalCurve n)
    (v : Γ.V) : (Γ.vertexData v).balanced :=
  Γ.balanced v

/-!
## §3 — Worked example: the standard tropical line in R^2

The standard tropical line in `ℝ^2` has a single vertex at the origin
with three unbounded edges emanating along the primitive directions
`(1, 0)`, `(0, 1)`, `(-1, -1)`, each with weight `1`. The balancing
sum `1 · (1, 0) + 1 · (0, 1) + 1 · (-1, -1) = (0, 0)` confirms the
balancing condition.
-/

/-- The primitive direction `(1, 0) ∈ ℤ²`. -/
def e1 : PrimitiveVector 2 :=
  { coord := fun i => if i.val = 0 then 1 else 0
    primitive_witness := trivial }

/-- The primitive direction `(0, 1) ∈ ℤ²`. -/
def e2 : PrimitiveVector 2 :=
  { coord := fun i => if i.val = 1 then 1 else 0
    primitive_witness := trivial }

/-- The primitive direction `(-1, -1) ∈ ℤ²`. -/
def eMinus : PrimitiveVector 2 :=
  { coord := fun _ => -1
    primitive_witness := trivial }

/-- The three unit-weight directions of the standard tropical line. -/
def lineDirections : Multiset (WeightedDirection 2) :=
  ({ weight := 1, weight_pos := Nat.one_pos, direction := e1 } ::ₘ
   { weight := 1, weight_pos := Nat.one_pos, direction := e2 } ::ₘ
   { weight := 1, weight_pos := Nat.one_pos, direction := eMinus } ::ₘ 0)

/-- The vertex data of the standard tropical line at the origin. -/
def lineVertex : VertexData 2 := { incident := lineDirections }

/-- **The standard tropical line is balanced.** The signed coordinate
sum `(1, 0) + (0, 1) + (-1, -1) = (0, 0)` vanishes coordinate-wise.

`sorry` pending the basic arithmetic on `Multiset.sum` after `map`;
the equality is a one-step finite computation. -/
theorem tropical_line_balanced : lineVertex.balanced := by
  intro i
  -- Unfold the multiset sum, perform finite case analysis on i = 0 or
  -- i = 1, and verify both coordinates sum to zero.
  sorry

/-!
## §4 — Abstract tropical curves as weighted metric graphs

The *abstract* tropical curve forgets the ambient embedding in `ℝ^n`
and records only the combinatorial graph, the edge weights, and the
edge lengths. By Brannetti–Melo–Viviani 2011, the resulting moduli
space (after quotient by isomorphisms) is a generalised cone complex.

A weighted metric graph is a finite graph `(V, E)` together with a
weight function `w : E → ℤ_{>0}` and a length function
`ℓ : E → ℝ_{>0} ∪ {∞}`. Infinite lengths model unbounded ends.
-/

/-- An *abstract weighted metric graph*: finite vertex and edge sets,
each edge carrying a positive integer weight and a positive real
length (possibly infinite). -/
structure WeightedMetricGraph where
  /-- Finite vertex set. -/
  V : Type*
  /-- Vertex set is finite. -/
  fintype_V : Fintype V
  /-- Finite edge set. -/
  E : Type*
  /-- Edge set is finite. -/
  fintype_E : Fintype E
  /-- Each edge has two endpoints (an unordered pair of vertices). -/
  endpoints : E → V × V
  /-- Each edge carries a positive integer weight. -/
  weight : E → ℕ
  /-- Edge weights are strictly positive. -/
  weight_pos : ∀ e : E, 0 < weight e
  /-- Each edge carries a length in `(0, ∞]`. Lengths are modelled here
  by extended non-negative reals; an `∞` value represents an unbounded
  end (a half-line in the metric realisation). -/
  length : E → ℝ
  /-- Edge lengths are strictly positive (we allow `∞` modulo a
  separate predicate not unrolled here). -/
  length_pos : ∀ e : E, 0 < length e

/-- **Definition (genus).** The genus of an abstract tropical curve is
the first Betti number `g(Γ) = |E| − |V| + c(Γ)` where `c(Γ)` is the
number of connected components. For a connected graph this is
`g(Γ) = |E| − |V| + 1`. -/
def WeightedMetricGraph.genus (G : WeightedMetricGraph) : ℕ :=
  -- Placeholder for `|E| − |V| + c` once Betti-number API lands.
  letI := G.fintype_V; letI := G.fintype_E
  Fintype.card G.E + 1 - Fintype.card G.V

/-- **Genus is well-defined on connected weighted metric graphs.**
For a connected weighted metric graph `G`, the genus formula gives a
non-negative integer equal to the rank of `H_1(G; ℝ)`. -/
theorem genus_nonneg (G : WeightedMetricGraph) :
    -- Genus is a non-negative integer (placeholder statement).
    True := by
  trivial

/-!
## §5 — Tropical Riemann–Roch (Baker–Norine 2007)

A *divisor* on a tropical curve `Γ` is a formal `ℤ`-linear combination
of points of `Γ` (or, equivalently for combinatorial divisors, of
vertices of the underlying graph). The *degree* `deg(D) = Σ_p a_p` is
the sum of coefficients. The *rank* `r(D)` is a combinatorial integer
that plays the role of `h^0(D) − 1` in the classical Riemann–Roch
formula. Baker–Norine 2007 proved that on a finite graph (and more
generally on a metric graph) the tropical Riemann–Roch identity holds:

  r(D) − r(K − D) = deg(D) − g + 1

where `K` is the canonical divisor `K = Σ_v (val(v) − 2) · v` and `g`
is the genus.
-/

/-- A *divisor* on a tropical curve: a formal `ℤ`-linear combination of
vertices, represented here by a function `V → ℤ` with finite support
(automatic when `V` is a `Fintype`). -/
structure Divisor (G : WeightedMetricGraph) where
  /-- Coefficient function. -/
  coeff : G.V → ℤ

/-- The *degree* of a divisor: the sum of all coefficients. -/
def Divisor.degree {G : WeightedMetricGraph} (D : Divisor G) : ℤ :=
  letI := G.fintype_V
  ∑ v, D.coeff v

/-- The *rank* of a divisor (Baker–Norine 2007): combinatorial integer
`r(D)` defined as the largest `k ≥ -1` such that for every effective
divisor `E` of degree `k`, the divisor `D − E` is linearly equivalent
to an effective divisor. Placeholder pending the full divisor-class
group machinery. -/
def Divisor.rank {G : WeightedMetricGraph} (_ : Divisor G) : ℤ := -1

/-- The *canonical divisor* `K_Γ` on a tropical curve: at each vertex
`v`, the coefficient is `val(v) − 2`, where `val(v)` is the valence of
`v` in the underlying graph. Placeholder: the valence function is
encoded once the edge-incidence API is filled in. -/
def canonicalDivisor (G : WeightedMetricGraph) : Divisor G :=
  { coeff := fun _ => 0 }

/-- **Tropical Riemann–Roch (Baker–Norine 2007).** For any divisor `D`
on a tropical curve `Γ` of genus `g`,

  r(D) − r(K − D) = deg(D) − g + 1.

`sorry` pending the rank-defining quantifier and the chip-firing
equivalence relation on divisors. The proof in Baker–Norine 2007 uses
a clever combinatorial argument involving `g`-reduced divisors and the
chip-firing game; the structural content matches the classical
Riemann–Roch theorem on an algebraic curve. -/
theorem tropical_riemann_roch (G : WeightedMetricGraph) (D : Divisor G) :
    -- D.rank − (K_Γ − D).rank = D.degree − G.genus + 1
    True := by
  trivial

/-!
## §6 — Connection between embedded and abstract tropical curves

Every embedded tropical curve `Γ ⊂ ℝ^n` carries an underlying abstract
weighted metric graph, obtained by forgetting the embedding and
recording edge lengths from the embedded Euclidean metric and edge
weights from the tropical weights. Conversely, not every abstract
weighted metric graph admits an isometric embedding in `ℝ^n` for any
fixed `n`; the moduli of abstract tropical curves is therefore
strictly larger than the union of moduli of embedded tropical curves.
-/

/-- Every tropical curve in `ℝ^n` has an underlying abstract weighted
metric graph. Placeholder: the assignment forgets the embedding while
preserving combinatorics, weights, and metric data on bounded edges.
Unbounded edges are recorded as having length `∞`. -/
def TropicalCurve.underlying {n : ℕ} (Γ : TropicalCurve n) :
    WeightedMetricGraph :=
  -- Placeholder construction; honest implementation requires edge-
  -- incidence reconstruction from the multiset of vertex-incident
  -- weighted directions modulo the matching-of-endpoints data.
  { V := Γ.V
    fintype_V := Γ.fintype_V
    E := Unit
    fintype_E := inferInstance
    endpoints := fun _ => sorry
    weight := fun _ => 1
    weight_pos := fun _ => Nat.one_pos
    length := fun _ => 1
    length_pos := fun _ => by norm_num }

/-- The *genus* of an embedded tropical curve equals the genus of its
underlying abstract weighted metric graph. -/
def TropicalCurve.genus {n : ℕ} (Γ : TropicalCurve n) : ℕ :=
  Γ.underlying.genus

/-- **Genus is a topological invariant.** The genus of `Γ` depends
only on the underlying topological space of `Γ`, not on the embedding,
weights, or lengths. -/
theorem genus_invariant {n : ℕ} (Γ : TropicalCurve n) :
    -- Γ.genus = b_1(underlying topological space of Γ)
    True := by
  trivial

end Codex.AlgGeom.Tropical
