import PageHeader from "../../components/PageHeader";
import DataTable from "../../components/DataTable";
import { MathBlock, MathInline } from "../../components/MathBlock";
import { consecutiveLegFamily, legFactors } from "../../math/triples";
import styles from "./triples.module.css";

export const config = { mode: "static" };

export function head() {
  return {
    title: "Pythagorean triples — Polymath",
    description:
      "Euclid's triple generator and Grant's consecutive-leg family, with the c−a = 2n² factor rule that lines up against electron-shell capacities.",
  };
}

export default function Triples() {
  const family = consecutiveLegFamily(8);
  const rows = family.map((t, i) => {
    const { cMinusA, cPlusA } = legFactors(t);
    return [i + 1, t.a, t.b, t.c, cMinusA, cPlusA];
  });

  return (
    <article>
      <PageHeader
        kicker="Foundations"
        title="Pythagorean triples"
        tier="real"
        lede="The 'force triangles' are ordinary Pythagorean triples. Everything on this page is standard, verifiable mathematics — the generators are centuries old."
      />

      <div class={styles.prose}>
        <h2>Euclid's generator</h2>
        <p>
          Every primitive triple comes from two integers{" "}
          <MathInline tex="m > n > 0" />:
        </p>
        <MathBlock tex="(m^2 - n^2,\ 2mn,\ m^2 + n^2)" />
        <p>
          For <MathInline tex="m=2,\ n=1" /> this gives{" "}
          <span class={styles.family}>(3, 4, 5)</span> — the seed Grant builds his whole stack from.
        </p>

        <h2>The consecutive-leg family</h2>
        <p>
          Grant leans on the special family where the hypotenuse is one more than the long leg
          (<MathInline tex="c = b + 1" />):
        </p>
        <MathBlock tex="(a, b, c) = (2n+1,\ 2n^2 + 2n,\ 2n^2 + 2n + 1)" />
        <p>
          This is genuinely correct for every <MathInline tex="n" /> — the table below is generated by
          the same code that is unit-tested in <code>src/math/triples.ts</code>.
        </p>
      </div>

      <DataTable
        columns={["n", "a", "b", "c", "c − a", "c + a"]}
        rows={rows}
        caption="The consecutive-leg family. c − a and c + a are exact perfect-double-squares."
      />

      <div class={styles.prose}>
        <h2>The factor rule</h2>
        <p>The two factors of each triple follow a clean pattern:</p>
        <MathBlock tex="c - a = 2n^2 \qquad c + a = 2(n+1)^2" />
        <p>
          So <MathInline tex="c - a" /> runs <span class={styles.family}>2, 8, 18, 32, 50, 72…</span> —
          which is exactly the electron-shell capacity rule <MathInline tex="2n^2" />. That arithmetic
          coincidence is real and verifiable.
        </p>
      </div>

      <p class={styles.note}>
        <strong>Where the framework begins:</strong> that <MathInline tex="c-a = 2n^2" /> matches shell
        capacities is a true numerical fact. The claim that this <em>explains</em> chemistry — that a triple
        <em> is</em> an electron shell — is Grant's interpretation, not established physics. We treat the
        identity as standard and the significance as a Grant construct.
      </p>
    </article>
  );
}
