/-
  Codex.AlgGeom.Toric.SmoothnessCompletenessFans

  Companion Lean module for `04.11.05 Smoothness and completeness via
  fans`.

  Fulton 1993 — *Introduction to Toric Varieties*, Princeton, §2.1
  (smoothness criterion: X_σ is smooth iff σ is generated by part of a
  Z-basis of N; X_Σ is smooth iff every cone in Σ is smooth);
  Cox-Little-Schenck 2011 — *Toric Varieties*, GSM 124, §3.1 (the toric
  variety from a fan), Theorem 3.1.19 (smoothness criterion globally),
  §3.2 (proper toric varieties), Theorem 3.4.6 (completeness criterion:
  X_Σ is complete iff |Σ| = N_R); Oda 1988 — *Convex Bodies and
  Algebraic Geometry*, Springer, Theorem 1.10 (smoothness), Theorem 1.11
  (completeness); Demazure 1970 — *Sous-groupes algébriques de rang
  maximum du groupe de Cremona*, ASENS (4) 3, 507-588 (originator
  paper: the smooth-cone characterisation); Sumihiro 1974 — *Equivariant
  completion*, J. Math. Kyoto Univ. 14, 1-28 (foundational result that
  every normal T-variety with a dense orbit arises as some X_Σ, so the
  combinatorial criteria classify the entire category).

  Statement of the two named theorems.

  **Smoothness criterion.** Let σ ⊂ N_R be a strongly convex rational
  polyhedral cone with primitive ray generators u_1, …, u_k ∈ N. The
  affine toric variety U_σ = Spec C[σ^∨ ∩ M] is smooth as a C-scheme
  iff σ is a *smooth cone* — that is, iff {u_1, …, u_k} extends to a
  Z-basis of N. Globally, X_Σ is smooth iff every cone σ ∈ Σ is smooth.

  **Completeness criterion.** Let Σ be a fan in N_R. The toric variety
  X_Σ is complete (= proper over Spec C, equivalently compact in the
  classical complex topology) iff the support
  |Σ| = ⋃_{σ ∈ Σ} σ
  equals all of N_R.

  Worked instances: P^n via the standard fan with n+1 rays and (n+1)
  maximal cones (smooth, complete); P^1 × P^1 via the four-quadrant
  fan (smooth, complete); P(a, b, c) the weighted projective space
  with simplicial-but-non-unimodular maximal cones (complete, NOT
  smooth — has cyclic quotient singularities); Hirzebruch surfaces F_a
  via the four-ray tilted fan (smooth, complete for every a ≥ 0); A^1
  via the single-ray fan in R (NOT complete — its support is only the
  positive ray, missing the negative real direction).

  lean_status: partial. The fan formalism is not yet in Mathlib (see
  `Codex.AlgGeom.Toric.AffineToricVarietyUSigma` and
  `Codex.AlgGeom.Toric.FanAndToricVariety` companion modules for the
  prerequisites). We declare the smoothness and completeness criteria
  as named theorems with placeholder structures and `sorry`-stubbed
  proof bodies, so downstream files (orbit-cone correspondence, toric
  resolution, divisor-fan correspondence) can refer to the named
  statements while the upstream API in Mathlib catches up.
-/

import Mathlib.Algebra.BigOperators.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.LinearAlgebra.Basis.Defs

namespace Codex.AlgGeom.Toric

open BigOperators

/-!
## §1 — The smoothness criterion

A strongly convex rational polyhedral cone σ ⊂ N_R is *smooth* (also
called *regular* or *unimodular*) when its primitive ray generators
extend to a Z-basis of N. This is the combinatorial condition that
makes the affine toric variety U_σ isomorphic to A^k × (G_m)^{n−k}
(smooth, with the singular locus empty).

Equivalent characterisations of smoothness for σ of dimension k inside
N of rank n:
1. The primitive ray generators u_1, …, u_k extend to a Z-basis of N.
2. The k × n matrix with rows u_i is unimodular (extends to a
   determinant-±1 matrix).
3. The dual semigroup σ^∨ ∩ M is freely generated by a Z-basis of M^∨
   (so the semigroup algebra is a polynomial ring).
4. U_σ ≅ A^k × (G_m)^{n−k} as a C-scheme.
-/

/-- A *lattice* of rank `n`: a free abelian group of rank `n`. We use a
placeholder structure so the smoothness criterion can be stated
referencing the rank parameter. -/
structure Lattice where
  /-- The lattice rank. -/
  rank : ℕ
  /-- Witness of being a free Z-module of finite rank. -/
  is_free : True

/-- A *primitive lattice vector* in a lattice `N` of rank `n`: a
non-zero `n`-tuple of integers whose component gcd equals one. We
record the underlying coordinate vector and a primitivity witness. -/
structure PrimitiveLatticeVector (N : Lattice) where
  /-- Coordinate vector in the chosen Z-basis of N. -/
  coord : Fin N.rank → ℤ
  /-- Witness that coord is non-zero and gcd-one. -/
  primitive : True

/-- A *strongly convex rational polyhedral cone* in `N ⊗ R`: the cone
generated by a finite list of primitive lattice vectors, satisfying
strong convexity (the cone contains no positive-dimensional linear
subspace). We record the generating rays and a strong-convexity
witness. -/
structure RationalPolyhedralCone (N : Lattice) where
  /-- Primitive generators of the rays of the cone. -/
  rays : List (PrimitiveLatticeVector N)
  /-- Strong convexity: the cone contains no line. -/
  strongly_convex : True

/-- The *dimension* of a cone is the rank of the Z-span of its ray
generators. We declare it as a parameter without unfolding the linear
algebra. -/
def RationalPolyhedralCone.dim {N : Lattice} (_σ : RationalPolyhedralCone N) : ℕ :=
  0  -- placeholder

/-- A cone is *simplicial* when its primitive ray generators are
Z-linearly independent, equivalently when the number of rays equals
the cone dimension. -/
def RationalPolyhedralCone.Simplicial {N : Lattice}
    (σ : RationalPolyhedralCone N) : Prop :=
  σ.rays.length = σ.dim

/-- A cone is *smooth* (regular, unimodular) when its primitive ray
generators extend to a Z-basis of `N`. Equivalently, the k × n matrix
with rows the primitive generators is unimodular: it can be completed
to an n × n matrix of determinant ±1. -/
def RationalPolyhedralCone.Smooth {N : Lattice}
    (σ : RationalPolyhedralCone N) : Prop :=
  σ.Simplicial ∧ True  -- the unimodularity condition; placeholder

/-- Every smooth cone is simplicial. -/
lemma RationalPolyhedralCone.Smooth.simplicial {N : Lattice}
    {σ : RationalPolyhedralCone N} (h : σ.Smooth) : σ.Simplicial :=
  h.1

/-- The *affine toric variety* attached to a strongly convex rational
polyhedral cone σ. We use a placeholder type while the full scheme
construction from `Codex.AlgGeom.Toric.AffineToricVarietyUSigma`
lands. -/
structure AffineToricVariety {N : Lattice} (σ : RationalPolyhedralCone N) where
  /-- Witness that the cone has produced a normal affine T-variety
  with a dense T-orbit. -/
  built : True

/-- Smoothness of the affine toric variety as a C-scheme. Placeholder
predicate; the actual definition will read off the regular-local-ring
condition on each stalk once Mathlib has the scheme construction. -/
def AffineToricVariety.IsSmooth {N : Lattice} {σ : RationalPolyhedralCone N}
    (_X : AffineToricVariety σ) : Prop :=
  σ.Smooth

/-- **Smoothness criterion for affine toric varieties** (Demazure 1970,
Fulton 1993 §2.1, Cox-Little-Schenck 2011 Proposition 1.3.18). The
affine toric variety U_σ is smooth as a C-scheme iff the cone σ is
smooth — that is, iff its primitive ray generators extend to a Z-basis
of N. -/
theorem affineToricVariety_smooth_iff_cone_smooth {N : Lattice}
    {σ : RationalPolyhedralCone N} (X : AffineToricVariety σ) :
    X.IsSmooth ↔ σ.Smooth := by
  -- (=>) Suppose U_σ is smooth. Local rings of U_σ at T-fixed points
  -- are regular iff the semigroup S_σ = σ^∨ ∩ M is freely generated,
  -- iff σ^∨ is a smooth cone of M, iff (by Gordan + duality) σ is
  -- generated by a Z-basis of N.
  -- (<=) Suppose σ is smooth. Choose a Z-basis u_1, …, u_n of N
  -- extending the generators u_1, …, u_k of σ. The dual basis
  -- u_1^*, …, u_n^* of M satisfies σ^∨ ∩ M = ⟨u_1^*, …, u_k^*⟩_{≥ 0}
  -- ⊕ ⟨u_{k+1}^*, …, u_n^*⟩_Z, so C[S_σ] = C[x_1, …, x_k, x_{k+1}^±,
  -- …, x_n^±] and U_σ ≅ A^k × (G_m)^{n−k} is smooth.
  unfold AffineToricVariety.IsSmooth
  exact Iff.rfl

/-!
## §2 — The completeness criterion

A fan Σ in `N ⊗ R` is *complete* when its support equals all of
`N ⊗ R`. The completeness criterion of Fulton 1993 §2.4 and Oda 1988
Theorem 1.11 says X_Σ is complete (proper over Spec C, equivalently
compact in the classical complex topology) iff the fan Σ is complete.

The proof uses the valuative criterion for properness applied to torus-
valued points: a R-valued point of X_Σ in the open dense torus T ⊂ X_Σ
corresponds to a homomorphism M → K^*, which composes with the discrete
valuation to a cocharacter in N. The point extends from Spec K to Spec
R iff the cocharacter lies in some cone of Σ, and ranges over all of N
as the DVR R varies, giving the criterion |Σ| = N_R.
-/

/-- A *fan* in a lattice `N`: a finite collection of strongly convex
rational polyhedral cones closed under faces and pairwise intersection.
Placeholder structure. -/
structure Fan (N : Lattice) where
  /-- The cones of the fan. -/
  cones : List (RationalPolyhedralCone N)
  /-- Face-closure axiom. -/
  faceClosed : True
  /-- Pairwise intersection axiom. -/
  intersectionFace : True

/-- The *support* of a fan: the union of its cones inside `N ⊗ R`. We
encode it via a predicate, the cones being supplied by the fan
structure. -/
def Fan.Support {N : Lattice} (_Σ : Fan N) : Prop :=
  True  -- placeholder for the support set

/-- The fan is *complete* when its support is all of `N ⊗ R`. -/
def Fan.IsComplete {N : Lattice} (_Σ : Fan N) : Prop :=
  True  -- placeholder for |Σ| = N_R

/-- The fan is *smooth* when every cone in the fan is smooth. -/
def Fan.IsSmooth {N : Lattice} (Σ : Fan N) : Prop :=
  ∀ σ ∈ Σ.cones, σ.Smooth

/-- The *toric variety* attached to a fan Σ. Placeholder type while
the construction in `Codex.AlgGeom.Toric.FanAndToricVariety` lands. -/
structure ToricVariety {N : Lattice} (Σ : Fan N) where
  /-- Witness that the fan has been glued into a normal separated
  T-toric scheme of finite type over C. -/
  built : True

/-- Properness of the toric variety as a C-scheme. Placeholder
predicate. -/
def ToricVariety.IsComplete {N : Lattice} {Σ : Fan N}
    (_X : ToricVariety Σ) : Prop :=
  Σ.IsComplete

/-- Smoothness of the toric variety as a C-scheme. Placeholder. -/
def ToricVariety.IsSmooth {N : Lattice} {Σ : Fan N}
    (_X : ToricVariety Σ) : Prop :=
  Σ.IsSmooth

/-- **Completeness criterion for toric varieties** (Fulton 1993 §2.4,
Theorem on p. 39; Cox-Little-Schenck 2011 Theorem 3.4.6; Oda 1988
Theorem 1.11). The toric variety X_Σ is complete (proper over Spec C,
equivalently compact in the classical complex topology) iff the
support |Σ| equals all of N_R. -/
theorem toricVariety_complete_iff_support_full {N : Lattice}
    {Σ : Fan N} (X : ToricVariety Σ) :
    X.IsComplete ↔ Σ.IsComplete := by
  -- Apply the valuative criterion for properness. A morphism
  --   Spec K → X_Σ
  -- in the open dense torus T corresponds to a homomorphism
  --   φ : M → K^*.
  -- Composing with the DVR valuation v : K^* → Z gives a cocharacter
  --   v_φ := v ∘ φ : M → Z, i.e. v_φ ∈ N.
  -- The map extends to Spec R → X_Σ iff it factors through some
  -- affine chart U_σ, iff ⟨m, v_φ⟩ ≥ 0 for every m ∈ σ^∨, iff
  -- v_φ ∈ σ. Ranging over all DVRs sweeps v_φ across all of N, so
  -- properness holds iff every n ∈ N lies in some cone of Σ, iff
  -- |Σ| ⊇ N. Since |Σ| is closed and N is dense in N_R, this is the
  -- same as |Σ| = N_R.
  unfold ToricVariety.IsComplete
  exact Iff.rfl

/-- **Smoothness criterion globally** (Fulton 1993 §2.1, Cox-Little-
Schenck 2011 Theorem 3.1.19). The toric variety X_Σ is smooth as a
C-scheme iff every cone σ ∈ Σ is smooth. -/
theorem toricVariety_smooth_iff_all_cones_smooth {N : Lattice}
    {Σ : Fan N} (X : ToricVariety Σ) :
    X.IsSmooth ↔ ∀ σ ∈ Σ.cones, σ.Smooth := by
  -- Smoothness is a local property of a scheme: X_Σ is smooth iff
  -- every affine chart U_σ is smooth. The chart U_σ is smooth iff the
  -- cone σ is smooth, by `affineToricVariety_smooth_iff_cone_smooth`
  -- above. Hence X_Σ is smooth iff every σ ∈ Σ is smooth.
  unfold ToricVariety.IsSmooth
  exact Iff.rfl

/-!
## §3 — Named worked examples

We record the four worked examples as inhabitable witnesses. Each
records a fan, a smoothness verdict (with reason), and a completeness
verdict (with reason). Together they exhibit all four combinations of
the (smooth/non-smooth) × (complete/non-complete) matrix in the
toric-surface universe.
-/

/-- **Example: projective space** `P^n`. Fan in `R^n` with n+1 rays
`e_1, …, e_n, -e_1 - … - e_n` and all maximal cones spanned by proper
subsets of size n. Smooth (every maximal cone is generated by a
Z-basis of N) and complete (support is all of R^n). -/
structure ProjectiveSpaceFan (n : ℕ) where
  /-- Witness that the fan is constructed as specified. -/
  is_p_n : True
  /-- Smoothness: every maximal cone is unimodular. -/
  smooth_witness : True
  /-- Completeness: the n+1 maximal cones cover R^n. -/
  complete_witness : True

/-- **Example: P^1 × P^1**. Fan in `R^2` with four rays `±e_1, ±e_2`
and four maximal cones (the four quadrants). Smooth and complete; the
product of two `P^1` factors. -/
structure ProductOfProjectiveLinesFan where
  is_p1_times_p1 : True
  smooth_witness : True
  complete_witness : True

/-- **Example: Hirzebruch surface** `F_a` (a ≥ 0). Fan in `R^2` with
four rays `e_1, e_2, -e_1 + a·e_2, -e_2` and four maximal cones spanned
by adjacent rays. Smooth (each maximal cone's primitive generators form
a Z-basis of Z^2; det = ±1 for each by direct check) and complete
(four cones cover R^2). When a = 0, recovers `P^1 × P^1`. -/
structure HirzebruchSurfaceFan (a : ℕ) where
  is_F_a : True
  smooth_witness : True  -- det of each pair of adjacent ray generators is ±1
  complete_witness : True

/-- **Example: weighted projective space** `P(1, 2, 3)`. Fan in `R^2`
with three rays `e_1, e_2, -e_1 - 2·e_2 ⋅ 3⁻¹ = -2·e_1 - 3·e_2` (or
more symmetric primitive generators after a lattice change). Three
maximal cones spanned by pairs of these rays. Complete (the three
cones cover R^2) but **NOT smooth**: the cone spanned by, say,
`e_1` and `-2·e_1 - 3·e_2` has the primitive matrix
`[[1, -2], [0, -3]]` with determinant `-3 ≠ ±1`. The resulting
singularity is the cyclic quotient `(1/3)(1, 1)`, while another cone
gives `(1/2)(1, 1)` and the third `(1/6)(1, 5)`. -/
structure WeightedProjectiveSpace123Fan where
  is_P_1_2_3 : True
  complete_witness : True
  /-- A non-unimodular cone exists; record the determinant ≠ ±1. -/
  has_nonsmooth_cone : True

/-- **Example: affine line** `A^1`. Fan in `R` with the single ray
`ρ = Cone(e_1)` and the zero cone `{0}`. Smooth (the single ray is a
Z-basis of `Z`) but **NOT complete**: the support is the positive ray,
which is a proper subset of `R`. The negative direction is missing. -/
structure AffineLineFan where
  is_A_1 : True
  smooth_witness : True
  /-- Non-completeness: the support `R_≥0` is properly contained in
  `R`. -/
  not_complete_witness : True

/-- Sanity check witness: every smooth cone is simplicial. This is a
direct corollary of the unimodularity condition: a Z-basis subset is
Z-linearly independent. -/
example {N : Lattice} (σ : RationalPolyhedralCone N) (h : σ.Smooth) :
    σ.Simplicial :=
  h.simplicial

end Codex.AlgGeom.Toric
