/-
  Codex.RepresentationTheory.Symmetric.SymmetricGroupRepresentation

  Companion Lean file for `07.05.01 Symmetric group representation`.
  lean_status: partial. Mathlib has `Equiv.Perm.cycleType`,
  `Combinatorics.Young.YoungDiagram`, and basic representation theory,
  but the Frobenius-Young classification (irreducibles of S_n indexed by
  partitions of n, with explicit Young symmetriser realisation) is not
  yet formalised.
-/

import Mathlib.GroupTheory.Perm.Cycle.Type
import Mathlib.Combinatorics.Young.YoungDiagram
import Mathlib.RepresentationTheory.Basic

namespace Codex.RepresentationTheory.Symmetric

-- Frobenius-Young classification:
--   {partitions of n} ↔ {irreducible S_n representations over ℂ}.
-- Each partition λ ⊢ n labels an irreducible V^λ realised as the
-- left ideal C[S_n] · c_λ generated by the Young symmetriser
-- c_λ = a_T · b_T (row symmetriser times signed column symmetriser).

end Codex.RepresentationTheory.Symmetric
