/-
  Codex.SpinGeometry.BergerHolonomy

  Berger holonomy classification and parallel spinors. Companion to the
  Master-tier unit `03.09.18 Berger holonomy classification + parallel
  spinors`. lean_status: partial — statements compile via stub types,
  with the Berger classification theorem and the Wang parallel-spinor
  bijection recorded as axioms pending Mathlib's holonomy-group and
  parallel-spinor infrastructure.
-/

import Mathlib.LinearAlgebra.CliffordAlgebra.Basic

namespace Codex.SpinGeometry.BergerHolonomy

/-- The holonomy group of a Riemannian connection on a manifold $M$:
    the subgroup of $\mathrm{O}(T_x M)$ generated by parallel transport
    around closed loops based at $x$.

    The fields are placeholders; the actual structure requires Mathlib's
    `Connection.parallelTransport` together with a Lie-subgroup formalism
    in the orthogonal group, none yet present in this combination. -/
structure HolonomyGroup (M : Type*) where
  /-- Underlying fibre type at a point. -/
  fibre : Type*
  /-- Riemannian metric data. -/
  riemann : Unit
  /-- Parallel-transport maps along piecewise-smooth loops. -/
  parallel_transport : Unit
  /-- Group structure: closure under composition and inverse. -/
  group_structure : Unit

/-- The seven Berger holonomy groups for irreducible non-symmetric
    Riemannian manifolds. -/
inductive BergerHolonomy
  | SO (n : ℕ)        -- generic
  | U (n : ℕ)         -- Kähler
  | SU (n : ℕ)        -- Calabi-Yau (parallel spinor)
  | Sp (n : ℕ)        -- hyperkähler (parallel spinor)
  | SpSp1 (n : ℕ)     -- quaternionic Kähler
  | G2                -- exceptional, dim 7 (parallel spinor)
  | Spin7             -- exceptional, dim 8 (parallel spinor)

/-- A parallel spinor on a Riemannian spin manifold: a section
    $\psi \in \Gamma(\mathfrak{S})$ with $\nabla^{LC, \mathfrak{S}} \psi = 0$
    everywhere. -/
structure ParallelSpinor {M : Type*} (E : HolonomyGroup M) where
  /-- The spinor field $\psi$ on $M$. -/
  psi : Unit
  /-- Parallel condition: $\nabla^{LC} \psi = 0$. -/
  parallel : Unit

/-! ### TODOs pending Mathlib coverage

Berger's classification theorem and Wang's parallel-spinor bijection
are stated as axioms. Each is a concrete Mathlib contribution target.
-/

/-- Berger classification (Berger 1955): the restricted holonomy of a
    simply-connected, irreducible, non-symmetric Riemannian manifold is
    one of the seven groups above.

    NOT YET IN MATHLIB. Requires (a) the Ambrose-Singer theorem identifying
    the holonomy Lie algebra as the curvature span, (b) the first Bianchi
    identity as a representation-theoretic constraint, (c) the case
    analysis of irreducible subalgebras of $\mathfrak{so}(n)$. -/
axiom berger_classification
    {M : Type*} (E : HolonomyGroup M) : True

/-- Wang's bijection (Wang 1989): a simply-connected Riemannian spin
    manifold admits a non-zero parallel spinor if and only if its
    restricted holonomy is one of $\mathrm{SU}(n), \mathrm{Sp}(n), G_2,
    \mathrm{Spin}(7)$.

    NOT YET IN MATHLIB. Requires (a) the spin representation $\Delta_n$
    of $\mathrm{Spin}(n)$, (b) branching rules for $\Delta_n$ under the
    inclusion of each special-holonomy group, (c) the parallel-spinor
    formalism on a spin manifold. -/
axiom wang_bijection
    {M : Type*} (E : HolonomyGroup M) : True

/-- Parallel-spinor count per holonomy: 2 for $\mathrm{SU}(n)$,
    $n+1$ for $\mathrm{Sp}(n)$, 1 for $G_2$, 1 for $\mathrm{Spin}(7)$.

    NOT YET IN MATHLIB. Requires the branching-rule calculations of
    Wang's theorem above. -/
axiom parallel_spinor_count
    {M : Type*} (E : HolonomyGroup M)
    (h : BergerHolonomy) : True

/-- Calabi-Yau is Ricci-flat (Yau 1977): a compact Kähler manifold with
    vanishing first Chern class admits a unique Kähler-Einstein metric
    with vanishing Ricci form in each Kähler class.

    NOT YET IN MATHLIB. Requires the Calabi conjecture, the complex
    Monge-Ampère equation, and the Kähler-Einstein metric existence theorem. -/
axiom calabi_yau_ricci_flat
    {M : Type*} (E : HolonomyGroup M) : True

/-- Bryant's local existence (Bryant 1987): metrics with $G_2$ holonomy
    exist locally in dimension 7, and metrics with $\mathrm{Spin}(7)$
    holonomy exist locally in dimension 8.

    NOT YET IN MATHLIB. Requires the Cartan-Kähler theorem applied to
    the exterior differential system encoding parallel calibration forms. -/
axiom bryant_local_existence
    {M : Type*} (E : HolonomyGroup M) : True

end Codex.SpinGeometry.BergerHolonomy
