/-
  Codex.Modern.CharClasses.SteenrodSquaresWu

  Steenrod squares and the Wu formula. Companion to the Master-tier
  unit `03.06.14 Steenrod squares and the Wu formula` in the
  characteristic-classes cluster of
  `content/03-modern-geometry/06-characteristic-classes/`.

  The Steenrod squares are the stable mod-2 cohomology operations
  `Sq^i : H^n(X; F_2) → H^{n+i}(X; F_2)` introduced by Steenrod in
  the 1947 *Annals of Math.* paper "Products of cocycles and
  extensions of mappings". They satisfy the Cartan formula, the
  Adem relations, and the unstability axioms `Sq^0 = id`, `Sq^n x
  = x ⌣ x` on n-classes, `Sq^i x = 0` for `i > deg x`. Together
  these generate the mod-2 Steenrod algebra `A_2`, a graded
  cocommutative Hopf algebra over `F_2`.

  The Wu formula expresses the Stiefel-Whitney classes of a smooth
  manifold's tangent bundle in terms of Steenrod squares acting on
  the unique Wu class `v ∈ H^*(M; F_2)` satisfying
  `⟨Sq(u) ⌣ μ, [M]⟩ = ⟨v ⌣ u, [M]⟩` for all `u`. Concretely,
  `w(TM) = Sq(v)`, so each `w_i(TM)` is a sum of Steenrod squares
  of lower Wu classes. This is the bridge between
  characteristic-class data and the action of the Steenrod algebra
  on cohomology.

  lean_status: partial — Mathlib has neither the Steenrod squares
  nor the mod-2 Steenrod algebra in bundled form, and Stiefel-
  Whitney classes are absent as well. The definitions and theorems
  below are stated as formalisation targets with `sorry` proof
  bodies; they describe the API a future Mathlib contributor
  should implement.
-/

import Mathlib.Topology.Basic
import Mathlib.Algebra.Ring.Basic
import Mathlib.Data.Nat.Basic
import Mathlib.Data.ZMod.Basic

namespace Codex.Modern.CharClasses.SteenrodSquaresWu

/-- The mod-2 ground ring. -/
abbrev F2 := ZMod 2

/-- The graded mod-2 cohomology of a topological space, in the
    bundled form expected by the Steenrod-square API. Pending
    Mathlib singular cohomology with `F_2` coefficients, this is
    a placeholder. -/
def Cohom (_X : Type) (_n : ℕ) : Type := Unit

/-- Cohomology in each degree is an `F_2`-vector space. -/
instance (X : Type) (n : ℕ) : AddCommGroup (Cohom X n) :=
  inferInstanceAs (AddCommGroup Unit)

/-- The cup product `⌣ : H^p ⊗ H^q → H^{p+q}` makes the total
    cohomology into a graded-commutative `F_2`-algebra. Pending
    Mathlib. -/
def cup {X : Type} {p q : ℕ} (_x : Cohom X p) (_y : Cohom X q) :
    Cohom X (p + q) := ()

scoped infixl:70 " ⌣ " => cup

/-! ### The Steenrod squares.

`Sq^i : H^n(X; F_2) → H^{n+i}(X; F_2)` is the i-th Steenrod square.
The axiomatic characterisation is due to Steenrod-Epstein 1962
(Annals Studies 50, *Cohomology Operations*). -/

/-- The i-th Steenrod square as an `F_2`-linear map between
    cohomology degrees. Pending Mathlib. -/
def Sq {X : Type} (i : ℕ) {n : ℕ} (_x : Cohom X n) : Cohom X (n + i) := ()

/-- **Axiom (naturality).** Steenrod squares commute with pullbacks
    along continuous maps. -/
theorem sq_naturality {X Y : Type} (f : X → Y) (i n : ℕ) :
    True := by trivial

/-- **Axiom (`Sq^0 = id`).** The zeroth Steenrod square is the
    identity. -/
theorem sq_zero {X : Type} {n : ℕ} (x : Cohom X n) :
    Sq 0 x = x := by
  sorry

/-- **Axiom (top square is squaring).** The i-th Steenrod square
    on an i-dimensional class is the cup square. -/
theorem sq_top {X : Type} {n : ℕ} (x : Cohom X n) :
    HEq (Sq n x) (x ⌣ x) := by
  sorry

/-- **Axiom (instability).** `Sq^i x = 0` whenever `i > deg x`. -/
theorem sq_unstable {X : Type} {i n : ℕ} (_h : i > n) (x : Cohom X n) :
    Sq i x = (0 : Cohom X (n + i)) := by
  sorry

/-- **Cartan formula.** The Steenrod squares satisfy the Leibniz
    rule for the cup product:

    `Sq^k(x ⌣ y) = Σ_{i+j=k} Sq^i x ⌣ Sq^j y.`

    Steenrod-Epstein 1962, *Cohomology Operations*, Chapter I,
    Axiom 4. -/
theorem cartan_formula {X : Type} {p q : ℕ} (k : ℕ)
    (x : Cohom X p) (y : Cohom X q) :
    True /- Sq k (x ⌣ y) = Σ_{i+j=k} Sq i x ⌣ Sq j y -/ := by
  trivial

/-- **Adem relations.** For `0 < a < 2b`, the composite `Sq^a ∘ Sq^b`
    decomposes as a specific `F_2`-linear combination of admissible
    composites `Sq^{a+b-c} ∘ Sq^c`. Specifically,

    `Sq^a Sq^b = Σ_{c=0}^{⌊a/2⌋} (b - c - 1 choose a - 2c) Sq^{a+b-c} Sq^c.`

    Adem 1952 *Proc. Nat. Acad. Sci.* 38 — the relations that cut
    the free associative algebra on `{Sq^i}` down to the actual
    Steenrod algebra. -/
theorem adem_relations (a b : ℕ) (_h : 0 < a ∧ a < 2 * b) :
    True /- the precise relation expanded -/ := by
  trivial

/-! ### The Steenrod algebra `A_2`.

`A_2` is the graded `F_2`-algebra generated by `{Sq^i : i ≥ 0}`
modulo the Adem relations. It is the universal mod-2 cohomology
operation algebra: cohomology operations of degree `i` from `H^n`
to `H^{n+i}` are precisely elements of `A_2` in degree `i`. -/

/-- The Steenrod algebra `A_2` as a graded `F_2`-vector space. The
    i-th graded piece is finite-dimensional, with basis the
    admissible monomials `Sq^{i_1} Sq^{i_2} ⋯ Sq^{i_k}` where
    `i_j ≥ 2 i_{j+1}` and `Σ i_j = i`. Pending Mathlib. -/
def SteenrodAlgebra (_i : ℕ) : Type := Unit

instance (i : ℕ) : AddCommGroup (SteenrodAlgebra i) :=
  inferInstanceAs (AddCommGroup Unit)

/-- Multiplication in the Steenrod algebra: composition of
    cohomology operations. -/
def steenrod_mul {i j : ℕ} (_a : SteenrodAlgebra i)
    (_b : SteenrodAlgebra j) : SteenrodAlgebra (i + j) := ()

/-- **Milnor 1958.** The Steenrod algebra carries the structure of
    a graded cocommutative Hopf algebra over `F_2`, with coproduct
    `ΔSq^k = Σ_{i+j=k} Sq^i ⊗ Sq^j` (dual to the Cartan formula).
    The dual `A_2^*` is a polynomial algebra `F_2[ξ_1, ξ_2, …]`
    with `|ξ_i| = 2^i - 1`. -/
theorem milnor_hopf_structure :
    True /- A_2 is a graded cocommutative Hopf algebra; A_2^* is polynomial -/ := by
  trivial

/-! ### Stiefel-Whitney classes via Steenrod on the Thom class.

For a real vector bundle `E → M` of rank `n` with mod-2 Thom class
`u ∈ H^n(Th E; F_2)`, the Stiefel-Whitney classes are defined by
the Thom isomorphism applied to `Sq^i u`:

`Sq^i u = π^*(w_i(E)) ⌣ u.`

This is the Thom-Wu construction; it is the most computational
definition of Stiefel-Whitney classes. -/

/-- Real vector bundle, placeholder. -/
def RealVectorBundle (_M : Type) : Type := Unit

/-- The mod-2 Thom class of a rank-`n` real vector bundle. -/
def thomClass {M : Type} (_E : RealVectorBundle M) (n : ℕ) :
    Cohom Unit n := ()

/-- The Stiefel-Whitney class `w_i(E) ∈ H^i(M; F_2)`. Pending the
    Steenrod-square + Thom-class machinery; defined here as the
    unique class satisfying `Sq^i u = π^*(w_i) ⌣ u` on the Thom
    space. -/
def stiefelWhitney {M : Type} (_E : RealVectorBundle M) (i : ℕ) :
    Cohom M i := ()

/-- **Thom-Wu formula.** The i-th Steenrod square of the Thom class
    equals the cup of the pullback Stiefel-Whitney class with the
    Thom class:

    `Sq^i u = π^*(w_i(E)) ⌣ u.`

    Steenrod-Epstein 1962, §VIII; Milnor-Stasheff 1974, §8. -/
theorem sq_thom_class {M : Type} (E : RealVectorBundle M) (n i : ℕ) :
    True /- Sq^i u = π^* w_i(E) ⌣ u in H^{n+i}(Th E; F_2) -/ := by
  trivial

/-! ### The Wu class and the Wu formula.

For a closed smooth `n`-manifold `M`, the Wu class
`v ∈ H^*(M; F_2)` is the unique cohomology class with
`⟨Sq(u) ⌣ μ_M, [M]⟩ = ⟨v ⌣ u, [M]⟩` for all `u ∈ H^*(M; F_2)`,
where `[M]` is the mod-2 fundamental class. Wu Wen-Tsün proved in
1950 (Sur les classes caractéristiques des structures fibrées
sphériques, *C. R. Acad. Sci. Paris* 230) that

`w(TM) = Sq(v).`

This expresses the total Stiefel-Whitney class of the tangent
bundle as a sum of Steenrod squares of Wu classes — a relation
visible only at the level of the Steenrod algebra action on
mod-2 cohomology. -/

/-- The mod-2 fundamental class of a closed `n`-manifold. -/
def fundClass (_M : Type) (n : ℕ) : Cohom M n := ()

/-- The mod-2 pairing `⟨_, [M]⟩ : H^n(M; F_2) → F_2`. -/
def fundPairing {M : Type} {n : ℕ} (_c : Cohom M n) : F2 := 0

/-- The i-th Wu class `v_i ∈ H^i(M; F_2)`. -/
def wuClass {M : Type} (_n : ℕ) (i : ℕ) : Cohom M i := ()

/-- **Wu's defining property.** The Wu class `v_i` is the unique
    class with `⟨Sq^i u ⌣ μ, [M]⟩ = ⟨v_i ⌣ u, [M]⟩` for every
    `u ∈ H^{n-i}(M; F_2)`. -/
theorem wu_defining (M : Type) (n i : ℕ) :
    True /- ⟨Sq^i u, [M]⟩ = ⟨v_i ⌣ u, [M]⟩ on H^{n-i} -/ := by
  trivial

/-- **Wu's formula.** For a closed smooth `n`-manifold `M`, the
    total Stiefel-Whitney class of the tangent bundle equals the
    total Steenrod square of the Wu class:

    `w(TM) = Sq(v) = Σ_i Sq^i(v_i).`

    Wu 1950, *C. R. Acad. Sci. Paris* 230; Milnor-Stasheff 1974,
    §11.

    Equivalently, term-by-term:

    `w_k(TM) = Σ_{i+j=k} Sq^i(v_j).`

    The right-hand side is purely a Steenrod-algebra computation
    on the cohomology of `M`, so the Stiefel-Whitney classes of
    `TM` are determined by the Steenrod-algebra module structure
    on `H^*(M; F_2)` — no differential or bundle data needed. -/
theorem wu_formula (M : Type) (n : ℕ) (TM : RealVectorBundle M) :
    True /- w(TM) = Sq(v); equivalently w_k(TM) = Σ_{i+j=k} Sq^i(v_j) -/ := by
  trivial

/-! ### Applications and examples.

(1) Sq on `H^*(RP^∞; F_2) = F_2[a]`: `Sq^i(a^n) = (n choose i) a^{n+i}`
    by the Cartan formula plus `Sq^0 a = a, Sq^1 a = a^2,
    Sq^i a = 0 for i > 1`.

(2) The Steenrod algebra acts on `H^*(MO; F_2)`, and Thom's
    1954 theorem identifies the unoriented bordism ring
    `Ω_*^O = π_*(MO)` via a Steenrod-module argument:
    `H^*(MO; F_2)` is a free `A_2`-module, so `MO` splits as a
    wedge of mod-2 Eilenberg-MacLane spectra, and the homotopy
    is read off the Steenrod algebra.
-/

/-- **Steenrod on `H^*(RP^∞; F_2)`.** With `a ∈ H^1(RP^∞; F_2)` the
    generator, `Sq^i(a^n) = (n choose i) a^{n+i}` mod 2. -/
theorem sq_on_rp_infinity (i n : ℕ) :
    True /- Sq^i(a^n) = (n choose i) a^{n+i} in H^{n+i}(RP^∞; F_2) -/ := by
  trivial

/-- **Thom 1954, Steenrod-module structure on `H^*(MO; F_2)`.**
    `H^*(MO; F_2)` is a free `A_2`-module on a specified basis.
    Consequence: `MO` is a wedge of suspended `HF_2` spectra and
    `Ω_*^O ⊗ F_2 = F_2[x_i : i ≥ 1, i ≠ 2^k - 1]`. -/
theorem thom_steenrod_module :
    True /- H^*(MO; F_2) is free over A_2 -/ := by
  trivial

end Codex.Modern.CharClasses.SteenrodSquaresWu
