// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/claims/constant-derivations"
    | "/claims/galaxies"
    | "/claims/primes-riemann"
    | "/codex/axioms"
    | "/codex/dimensions"
    | "/codex/imaginary-unit"
    | "/elements"
    | "/elements/isotopes"
    | "/elements/shells"
    | "/foundations/constants"
    | "/foundations/metallic-means"
    | "/foundations/nine-means"
    | "/foundations/triples"
    | "/foundations/unit-hyperbola"
    | "/generator/construction-rules"
    | "/generator/force-stack"
    | "/generator/new-numbers"
    | "/how-to-read"
    | "/resonance/spectral-chords"
    | "/resonance/tuning"
    | "/solids/120-cell"
    | "/solids/harmonic-solids"
    | "/solids/projection-theorem"
    | "/solids/standard"
    | "/wisdom/sacred-sites"
  }
}

export {};
