import Mathlib.MeasureTheory.MeasurableSpace.Basic
import Mathlib.MeasureTheory.MeasurableSpace.Defs
import Mathlib.MeasureTheory.Constructions.BorelSpace.Basic
import Mathlib.Topology.Basic

namespace Codex.Analysis.MeasureTheory

/-!
Companion names for the σ-algebra and Borel σ-algebra unit.

Mathlib represents a σ-algebra on a type `X` by the `MeasurableSpace X`
typeclass.  Membership of a set `s : Set X` in that σ-algebra is recorded
by `MeasurableSet s`.  The Borel σ-algebra on a topological space is the
σ-algebra generated by the open sets and is available as `borel`.
-/

variable (X : Type*) [MeasurableSpace X]

/-- A "measurable space" in the sense of the unit. -/
abbrev IsSigmaAlgebra : Prop := True
-- Placeholder: Mathlib's `MeasurableSpace` typeclass already encodes the
-- σ-algebra axioms; this companion simply records the unit's intended
-- predicate name.  Downstream measure-theoretic constructions in this
-- module live in `Codex.Analysis.MeasureTheory.*` and import the standard
-- Mathlib definitions.

variable (Y : Type*) [TopologicalSpace Y]

/-- The Borel σ-algebra on a topological space, named for cross-reference. -/
abbrev CodexBorel : MeasurableSpace Y := borel Y

end Codex.Analysis.MeasureTheory
