/-
  Codex.ModernGeometry.TensorAlgebra.TensorProduct

  Companion Lean file for `03.01.01 Tensor product`.
-/

import Mathlib.LinearAlgebra.TensorProduct.Basic

namespace Codex.ModernGeometry.TensorAlgebra

open TensorProduct

variable {K V W : Type*} [CommSemiring K]
variable [AddCommMonoid V] [Module K V] [AddCommMonoid W] [Module K W]

/-- Pure tensors are supplied by Mathlib's `TensorProduct.tmul`. -/
abbrev pureTensor (v : V) (w : W) : TensorProduct K V W :=
  TensorProduct.tmul K v w

/-- The tensor product is generated by pure tensors subject to bilinearity. -/
theorem pureTensor_add_left (v v' : V) (w : W) :
    pureTensor (K := K) (v + v') w =
      pureTensor (K := K) v w + pureTensor (K := K) v' w :=
  TensorProduct.add_tmul v v' w

end Codex.ModernGeometry.TensorAlgebra
