// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/elements"
    | "/elements/shells"
    | "/foundations/constants"
    | "/foundations/kepler-triangle"
    | "/foundations/metallic-means"
    | "/foundations/nine-means"
    | "/foundations/triples"
    | "/foundations/unit-hyperbola"
    | "/methodology"
    | "/resonance/spectral-chords"
    | "/resonance/tuning"
    | "/solids/standard"
  }
}

export {};
