/-
  Codex — top-level Lean library.

  Each curriculum unit at `lean_status: full` or `lean_status: partial`
  has a corresponding module under `Codex/<Section>/<Slug>.lean`.
  This file imports the full set so `lake build` checks all of them.

  GENERATED FILE — do not hand-edit the import list. It mirrors every
  module under `lean/Codex/`, sorted by path. Regenerate with
  `python3 scripts/check_codex_imports.py --fix`; `scripts/validate_all.py`
  fails on divergence.
-/

import Codex.AlgGeom.Hodge.AkizukiNakanoVanishing
import Codex.AlgGeom.Hodge.DdbarLemma
import Codex.AlgGeom.Hodge.HardLefschetz
import Codex.AlgGeom.Hodge.HodgeRiemannBilinear
import Codex.AlgGeom.Hodge.KodairaEmbedding
import Codex.AlgGeom.Hodge.LefschetzOneOne
import Codex.AlgGeom.Moduli.HilbertMumford
import Codex.AlgGeom.Moduli.HilbertScheme
import Codex.AlgGeom.Moduli.KempfNess
import Codex.AlgGeom.Moduli.KirwanStratification
import Codex.AlgGeom.Moduli.VariationOfGIT
import Codex.AlgGeom.Moduli.VectorBundlesCurveSlopeStability
import Codex.AlgGeom.Toric.DivisorSupportFunction
import Codex.AlgGeom.Toric.OrbitConeCorrespondence
import Codex.AlgGeom.Toric.PicardGroup
import Codex.AlgGeom.Toric.PolytopeFanDictionary
import Codex.AlgGeom.Toric.ResolutionSingularities
import Codex.AlgGeom.Toric.SmoothnessCompletenessFans
import Codex.AlgGeom.Tropical.DualIntersectionComplex
import Codex.AlgGeom.Tropical.GrossSiebertReconstruction
import Codex.AlgGeom.Tropical.KapranovTheorem
import Codex.AlgGeom.Tropical.LogGromovWitten
import Codex.AlgGeom.Tropical.MikhalkinCorrespondence
import Codex.AlgGeom.Tropical.NewtonPolytopeAmoeba
import Codex.AlgGeom.Tropical.NishinouSiebertCorrespondence
import Codex.AlgGeom.Tropical.PeriodIntegral
import Codex.AlgGeom.Tropical.SlabFunction
import Codex.AlgGeom.Tropical.StromingerYauZaslow
import Codex.AlgGeom.Tropical.ThetaFunction
import Codex.AlgGeom.Tropical.ToricDegeneration
import Codex.AlgGeom.Tropical.TropicalCurve
import Codex.AlgGeom.Tropical.TropicalSemiringPolynomial
import Codex.AlgebraicGeometry.Coherent.Coherent
import Codex.AlgebraicGeometry.Coherent.QuasiCoherent
import Codex.AlgebraicGeometry.Cohomology.SheafCohomology
import Codex.AlgebraicGeometry.Differentials.CanonicalSheaf
import Codex.AlgebraicGeometry.Differentials.Differentials
import Codex.AlgebraicGeometry.Differentials.SerreDuality
import Codex.AlgebraicGeometry.Divisors.Ample
import Codex.AlgebraicGeometry.Divisors.CartierDivisor
import Codex.AlgebraicGeometry.Divisors.LineBundle
import Codex.AlgebraicGeometry.Divisors.PicardGroup
import Codex.AlgebraicGeometry.Divisors.WeilDivisor
import Codex.AlgebraicGeometry.Hodge.HodgeDecomposition
import Codex.AlgebraicGeometry.Hodge.KodairaVanishing
import Codex.AlgebraicGeometry.Moduli.GIT
import Codex.AlgebraicGeometry.Moduli.ModuliOfCurves
import Codex.AlgebraicGeometry.Projective.Blowup
import Codex.AlgebraicGeometry.Projective.ProjectiveSpace
import Codex.AlgebraicGeometry.RiemannRoch.Curves
import Codex.AlgebraicGeometry.Schemes.AffineScheme
import Codex.AlgebraicGeometry.Schemes.Morphism
import Codex.AlgebraicGeometry.Schemes.ProjectiveScheme
import Codex.AlgebraicGeometry.Schemes.Scheme
import Codex.AlgebraicGeometry.Sheaves.DirectInverseImage
import Codex.AlgebraicGeometry.Sheaves.Sheaf
import Codex.AlgebraicGeometry.Sheaves.Sheafification
import Codex.AlgebraicGeometry.Sheaves.Stalk
import Codex.Analysis.FunctionalAnalysis.BanachSpaces
import Codex.Analysis.FunctionalAnalysis.BoundedOperators
import Codex.Analysis.FunctionalAnalysis.CompactOperators
import Codex.Analysis.FunctionalAnalysis.HahnBanach
import Codex.Analysis.FunctionalAnalysis.HilbertSpace
import Codex.Analysis.FunctionalAnalysis.OpenMapping
import Codex.Analysis.Harmonic.FourierSeries
import Codex.Analysis.Harmonic.FourierTransform
import Codex.Analysis.MeasureTheory.AbsoluteContinuityRadonNikodym
import Codex.Analysis.MeasureTheory.FatouDCT
import Codex.Analysis.MeasureTheory.FubiniTonelli
import Codex.Analysis.MeasureTheory.LebesgueIntegralMCT
import Codex.Analysis.MeasureTheory.LpSpaces
import Codex.Analysis.MeasureTheory.MeasurableFunctionsEgorovLusin
import Codex.Analysis.MeasureTheory.OuterMeasureCaratheodory
import Codex.Analysis.MeasureTheory.SigmaAlgebraBorel
import Codex.Analysis.MultiVariable.ChainRule
import Codex.Analysis.MultiVariable.ImplicitInverse
import Codex.Analysis.MultiVariable.LimitContinuity
import Codex.Analysis.MultiVariable.TaylorExtrema
import Codex.Analysis.RealNumbers.Axioms
import Codex.Analysis.Sequences.CauchyBolzanoWeierstrass
import Codex.Analysis.Topology.MetricSpace
import Codex.Analysis.Topology.TopologicalSpace
import Codex.Bundles.SphereBundle
import Codex.DifferentialForms.Kunneth
import Codex.DifferentialForms.SingularCohomology
import Codex.Foundations.LinearAlgebra.Basis
import Codex.Foundations.LinearAlgebra.BilinearQuadraticForm
import Codex.Foundations.LinearAlgebra.Determinant
import Codex.Foundations.LinearAlgebra.Eigen
import Codex.Foundations.LinearAlgebra.Field
import Codex.Foundations.LinearAlgebra.JordanForm
import Codex.Foundations.LinearAlgebra.RankNullity
import Codex.Foundations.LinearAlgebra.SVD
import Codex.Foundations.LinearAlgebra.VectorSpace
import Codex.Homotopy.SullivanMinimalModels
import Codex.Homotopy.WhiteheadTower
import Codex.KTheory.UniversalBundle
import Codex.Modern.CharClasses.BorelHirzebruchGT
import Codex.Modern.CharClasses.ChernCharacter
import Codex.Modern.CharClasses.ChernSimonsTransgression
import Codex.Modern.CharClasses.ExoticSpheres
import Codex.Modern.CharClasses.HirzebruchSignature
import Codex.Modern.CharClasses.MultiplicativeSequences
import Codex.Modern.CharClasses.OrientedBordismPT
import Codex.Modern.CharClasses.SWPontryaginNumbers
import Codex.Modern.CharClasses.SignatureIntersectionForm
import Codex.Modern.CharClasses.SteenrodSquaresWu
import Codex.Modern.CharClasses.UnorientedBordismThom
import Codex.Modern.CharClasses.WhitneyDualityImmersion
import Codex.Modern.Homotopy.ArithmeticSquare
import Codex.Modern.Homotopy.BousfieldKanSpectralSequence
import Codex.Modern.Homotopy.HomotopyColimitBK
import Codex.Modern.Homotopy.KanQuillenModelStructure
import Codex.Modern.Homotopy.PostnikovTowerKan
import Codex.Modern.Homotopy.SimplicialModelCategory
import Codex.Modern.KTheory.KRTheory
import Codex.ModernGeometry.DifferentialForms.CechDeRham
import Codex.ModernGeometry.DifferentialForms.DeRhamCohomology
import Codex.ModernGeometry.DifferentialForms.DifferentialForms
import Codex.ModernGeometry.DifferentialForms.ExteriorDerivative
import Codex.ModernGeometry.DifferentialForms.GoodCover
import Codex.ModernGeometry.DifferentialForms.LieAlgebra
import Codex.ModernGeometry.DifferentialForms.MayerVietoris
import Codex.ModernGeometry.DifferentialForms.StokesTheorem
import Codex.ModernGeometry.DifferentialForms.ThomGlobalAngularForm
import Codex.ModernGeometry.Homotopy.CoveringSpace
import Codex.ModernGeometry.Homotopy.Homotopy
import Codex.ModernGeometry.Homotopy.Suspension
import Codex.ModernGeometry.Lie.LieGroup
import Codex.ModernGeometry.Manifolds.SmoothManifold
import Codex.ModernGeometry.TensorAlgebra.AssociativeAlgebra
import Codex.ModernGeometry.TensorAlgebra.Ideal
import Codex.ModernGeometry.TensorAlgebra.TensorProduct
import Codex.NumberTheory.GaloisReps.EllAdic
import Codex.NumberTheory.Iwasawa.PadicL
import Codex.NumberTheory.Iwasawa.ZpExtensions
import Codex.NumberTheory.LFunctions.DedekindHeckeArtin
import Codex.NumberTheory.LFunctions.DirichletL
import Codex.NumberTheory.LFunctions.RiemannZeta
import Codex.NumberTheory.ModularForms.EichlerShimura
import Codex.NumberTheory.ModularForms.HeckeOperators
import Codex.NumberTheory.ModularForms.SL2Z
import Codex.NumberTheory.Modularity.ModularityBSD
import Codex.Precalc.Equations.LinesPlane
import Codex.Precalc.Equations.QuadraticFormula
import Codex.Precalc.Inequalities.Basic
import Codex.Precalc.Numbers.AbsoluteValue
import Codex.Precalc.Numbers.Polynomials
import Codex.Precalc.Numbers.Reals
import Codex.Precalc.SetAndFunction.Function
import Codex.RepresentationTheory.Character.Maschke
import Codex.RepresentationTheory.Classification.CartanWeyl
import Codex.RepresentationTheory.CompactLie.CompactLieGroupRepresentation
import Codex.RepresentationTheory.CompactLie.HaarMeasure
import Codex.RepresentationTheory.CompactLie.PeterWeylTheorem
import Codex.RepresentationTheory.Foundations.Character
import Codex.RepresentationTheory.Foundations.CharacterOrthogonality
import Codex.RepresentationTheory.Foundations.FrobeniusReciprocity
import Codex.RepresentationTheory.Foundations.GroupRepresentation
import Codex.RepresentationTheory.Foundations.InducedRepresentation
import Codex.RepresentationTheory.Foundations.RegularRepresentation
import Codex.RepresentationTheory.Foundations.SchurLemma
import Codex.RepresentationTheory.Foundations.TensorProduct
import Codex.RepresentationTheory.HighestWeight.HighestWeight
import Codex.RepresentationTheory.LieAlgebraic.BorelWeilTheorem
import Codex.RepresentationTheory.LieAlgebraic.DynkinDiagram
import Codex.RepresentationTheory.LieAlgebraic.LieAlgebraRepresentation
import Codex.RepresentationTheory.LieAlgebraic.RootSystem
import Codex.RepresentationTheory.LieAlgebraic.UniversalEnvelopingAlgebra
import Codex.RepresentationTheory.LieAlgebraic.VermaModule
import Codex.RepresentationTheory.LieAlgebraic.WeylCharacterFormula
import Codex.RepresentationTheory.LieAlgebraic.WeylDimensionFormula
import Codex.RepresentationTheory.LieAlgebraic.WeylGroup
import Codex.RepresentationTheory.Symmetric.SpechtModule
import Codex.RepresentationTheory.Symmetric.SymmetricGroupRepresentation
import Codex.RepresentationTheory.Symmetric.YoungDiagram
import Codex.RiemannSurfaces.BranchPoints.BranchPointRamification
import Codex.RiemannSurfaces.ComplexAnalysis.AnalyticContinuation
import Codex.RiemannSurfaces.ComplexAnalysis.CauchyIntegralFormula
import Codex.RiemannSurfaces.ComplexAnalysis.CauchyRiemann
import Codex.RiemannSurfaces.ComplexAnalysis.Holomorphic
import Codex.RiemannSurfaces.ComplexAnalysis.MeromorphicFunction
import Codex.RiemannSurfaces.ComplexAnalysis.ResidueTheorem
import Codex.RiemannSurfaces.ComplexAnalysis.RiemannMappingTheorem
import Codex.RiemannSurfaces.DivisorsBundles.DivisorRiemannSurface
import Codex.RiemannSurfaces.DivisorsBundles.HolomorphicLineBundle
import Codex.RiemannSurfaces.DivisorsBundles.RiemannHurwitzFormula
import Codex.RiemannSurfaces.Jacobians.AbelJacobiMap
import Codex.RiemannSurfaces.Jacobians.HolomorphicOneForm
import Codex.RiemannSurfaces.Jacobians.JacobianVariety
import Codex.RiemannSurfaces.Jacobians.PeriodMatrix
import Codex.RiemannSurfaces.Jacobians.ThetaFunction
import Codex.RiemannSurfaces.RiemannRoch.CompactSurface
import Codex.RiemannSurfaces.SeveralVariables.HartogsPhenomenon
import Codex.RiemannSurfaces.SeveralVariables.HolomorphicSeveralVariables
import Codex.RiemannSurfaces.Surfaces.GenusRiemannSurface
import Codex.RiemannSurfaces.Surfaces.RiemannSurface
import Codex.RiemannSurfaces.Surfaces.UniformizationTheorem
import Codex.SpectralSequences.LerayHirschSplitting
import Codex.SpectralSequences.LeraySerre
import Codex.SpectralSequences.SpectralSequence
import Codex.SpinGeometry.BergerHolonomy
import Codex.SpinGeometry.CalibratedGeometries
import Codex.SpinGeometry.CliffordAlgebra
import Codex.SpinGeometry.CliffordChessboard
import Codex.SpinGeometry.ClkDirac
import Codex.SpinGeometry.DiracBundle
import Codex.SpinGeometry.KRTheory
import Codex.SpinGeometry.PSCObstruction
import Codex.SpinGeometry.Pseudodifferential
import Codex.SpinGeometry.Triality
import Codex.SpinGeometry.WittenPositiveMass
import Codex.StatMech.QFT.PhiFourDyson
